services:
  app:
    image: crpi-v5h0koewouiw970u.cn-shanghai.personal.cr.aliyuncs.com/ebook-pdf-downloader-docker/ebook-pdf-downloader-docker:latest
    container_name: book-downloader
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    volumes:
      - ./local-test/downloads:/downloads
      - ./local-test/finished:/finished
      - ./local-test/tmp:/tmp/bdw
      - ./local-test/db:/db
      - config_data:/app/data
    restart: "no"

  stacks:
    image: crpi-v5h0koewouiw970u.cn-shanghai.personal.cr.aliyuncs.com/ebook-pdf-downloader-docker/stacks:latest
    container_name: stacks
    stop_signal: SIGTERM
    stop_grace_period: 30s
    ports:
      - "7788:7788"
    volumes:
      - ./local-test/stacks-config:/opt/stacks/config
      - ./local-test/downloads:/opt/stacks/download
      - ./local-test/stacks-logs:/opt/stacks/logs
    environment:
      - USERNAME=admin
      - PASSWORD=password
      - SOLVERR_URL=flaresolverr:8191
      - TZ=Asia/Shanghai
    restart: "no"

  flaresolverr:
    image: crpi-v5h0koewouiw970u.cn-shanghai.personal.cr.aliyuncs.com/ebook-pdf-downloader-docker/flaresolverr:latest
    container_name: flaresolverr
    ports:
      - "8191:8191"
    environment:
      - LOG_LEVEL=info
    restart: "no"

volumes:
  config_data:
