services:
  app:
    image: crpi-v5h0koewouiw970u.cn-shanghai.personal.cr.aliyuncs.com/ebook-pdf-downloader-docker/ebook-pdf-downloader-docker:latest
    container_name: book-downloader
    ports:
      - "8000:8000"
    volumes:
      - ./downloads:/downloads
      - ./finished:/finished
      - ./tmp:/tmp/bdw
      - ./db:/db
      - config_data:/app/data
    restart: unless-stopped

  stacks:
    image: zelest/stacks:latest
    container_name: stacks
    stop_signal: SIGTERM
    stop_grace_period: 30s
    ports:
      - "7788:7788"
    volumes:
      - ./stacks-config:/opt/stacks/config
      - ./downloads:/opt/stacks/download
      - ./stacks-logs:/opt/stacks/logs
    environment:
      - USERNAME=admin
      - PASSWORD=请修改此密码
      - SOLVERR_URL=flaresolverr:8191
      - TZ=Asia/Shanghai
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    ports:
      - "8191:8191"
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped

volumes:
  config_data:
