services:
  app:
    image: crpi-v5h0koewouiw970u.cn-shanghai.personal.cr.aliyuncs.com/ebook-pdf-downloader-docker/ebook-pdf-downloader-docker:latest
    container_name: book-downloader
    ports:
      - "8000:8000"
    volumes:
      - /share/Public/ebook/downloads:/downloads
      - /share/Public/ebook/finished:/finished
      - /share/Public/ebook/tmp:/tmp/bdw
      - /share/Public/ebook/db:/db
      - ebook_config:/app/data
    restart: unless-stopped

  stacks:
    image: ghcr.io/callioper/book-searcher:latest
    container_name: book-searcher
    ports:
      - "7788:7788"
    volumes:
      - /share/Public/ebook/db:/data
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    ports:
      - "8191:8191"
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped

volumes:
  ebook_config:
